spring:
  application:
    name: Subscribe Master

  profiles:
    active: dev

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

jwt:
  secretKey: 1875769ca11cc30bc1d820c10a2218ec3350abc9268dfff821ce8e4a969bf6f9
