spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/subscribe_master"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}